/**
 * @author Samson Leung 110490519
 */
package csg;

public enum CsgProp {
    COURSE_TAB,
    TA_TAB,
    RECITATION_TAB,
    SCHEDULE_TAB,
    PROJECT_TAB,
    
    // Course Details Tab
    COURSE_INFO,
    SUBJECT,NUMBER,SEMESTER,YEAR,TITLE,NAME,HOME,EXPORT,
    SITE_TEMPLATE,
    PAGE_STYLE,
    BANNER_IMAGE_LABEL, LEFT_IMAGE_LABEL, RIGHT_IMAGE_LABEL, STYLESHEET_LABEL, 
    NOTE_LABEL, CHANGE_BUTTON, SITE_PAGES, USE, NAVBAR, FILE_NAME, SCRIPT, 
    NONE_SELECTED, SELECT_EXPORT, SELECTED_DIRECTORY, SELECT_TEMPLATE,
    
    // Recitations Tab
    RECITATIONS_LABEL,
    SECTION_COL, INSTRUCTOR_COL, DAYTIME_COL, LOCATION_COL, TA_COL,
    ADD_LABEL, SECTION_LABEL, INSTRUCTOR_LABEL, DAYTIME_LABEL, LOCATION_LABEL,
    TA_LABEL, ADD_UPDATE_BUTTON, CLEAR_BUTTON, 
    
    //Schedule Tab
    CRITERIA_LABEL, SCHEDULE_LABEL, FRIDAY_LABEL, MONDAY_LABEL, CALENDAR_LABEL, 
    ITEMS_LABEL, ADD_EDIT_LABEL, TYPE_LABEL, DATE_LABEL, TIME_LABEL, TITLE_LABEL, 
    TOPIC_LABEL, LINK_LABEL, TOPIC_COL, DATE_COL, TITLE_COL, TYPE_COL,
    
    // Projects Tab
    PROJECTS_LABEL, TEAMS_LABEL, STUDENTS_LABEL, NAME_COL, COLOR_COL, 
    TEXT_COLOR_COL, LINK_COL, FIRST_NAME_COL, LAST_NAME_COL, TEAM_COL, ROLE_COL, 
    NAME_LABEL, COLOR_LABEL, TEXT_COLOR_LABEL,
    
    // TA Tab
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    ENTER_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    TIMES,
    TIMES_TITLE,
    INVALID_TIMES,
    INVALID_TIMES_TITLE,
    INVALID_TA_EMAIL_TITLE,
    INVALID_TA_EMAIL_MESSAGE,
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    START_TIME,
    END_TIME,
    
    TA_EMAIL_INVALID_TITLE,
    TA_EMAIL_INVALID_MESSAGE,
    
    OFFICE_HOURS_REMOVED_TITLE,
    START_OVER_END_TITLE,
    START_OVER_END_MESSAGE,
    OFFICE_HOURS_REMOVED_MESSAGE,
    CHECK_TEXT,
    
    TIME_12AM,
    TIME_1AM,
    TIME_2AM,
    TIME_3AM,
    TIME_4AM,
    TIME_5AM,
    TIME_6AM,
    TIME_7AM,
    TIME_8AM,
    TIME_9AM,
    TIME_10AM,
    TIME_11AM,
    TIME_12PM,
    TIME_1PM,
    TIME_2PM,
    TIME_3PM,
    TIME_4PM,
    TIME_5PM,
    TIME_6PM,
    TIME_7PM,
    TIME_8PM,
    TIME_9PM,
    TIME_10PM,
    TIME_11PM,
}
